project_name: erigon

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: linux-amd64
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    tags: [ nosqlite, noboltdb, netgo ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  # - id: linux-arm64
  #   main: ./cmd/erigon
  #   binary: erigon
  #   goos: [ linux ]
  #   goarch: [ arm64 ]
  #   env:
  #     - CC=aarch64-linux-gnu-gcc
  #     - CXX=aarch64-linux-gnu-g++
  #   tags: [ nosqlite, noboltdb, netgo ]
  #   ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  # - id: windows-amd64
  #   main: ./cmd/erigon
  #   binary: erigon
  #   goos: [ windows ]
  #   goarch: [ amd64 ]
  #   env:
  #     - CC=x86_64-w64-mingw32-gcc
  #     - CXX=x86_64-w64-mingw32-g++
  #   tags: [ nosqlite, noboltdb, netgo ]
  #   ldflags: -s -w


snapshot:
  name_template: "{{ .Tag }}.next"

dockers:
  - image_templates:
      - settlemint/bsc-erigon:{{ .Version }}-amd64
      - ghcr.io/settlemint/bsc-erigon:{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    skip_push: true
    goarch: amd64
    ids:
      - linux-amd64
    build_flag_templates:
      - --platform=linux/amd64

  # - image_templates:
  #     - settlemint/bsc-erigon:{{ .Version }}-arm64
  #     - ghcr.io/settlemint/bsc-erigon:{{ .Version }}-arm64
  #   dockerfile: Dockerfile.release
  #   skip_push: true
  #   use: buildx
  #   goarch: arm64
  #   ids:
  #     - linux-arm64
  #   build_flag_templates:
  #     - --platform=linux/arm64/v8

docker_manifests:
  - name_template: settlemint/bsc-erigon:{{ .Version }}
    skip_push: true
    image_templates:
      - settlemint/bsc-erigon:{{ .Version }}-amd64
      # - settlemint/bsc-erigon:{{ .Version }}-arm64

  - name_template: ghcr.io/settlemint/bsc-erigon:{{ .Version }}
    skip_push: true
    image_templates:
      - ghcr.io/settlemint/bsc-erigon:{{ .Version }}-amd64
      # - ghcr.io/settlemint/bsc-erigon:{{ .Version }}-arm64

  - name_template: settlemint/bsc-erigon:latest
    skip_push: true
    image_templates:
      - settlemint/bsc-erigon:{{ .Version }}-amd64
      # - settlemint/bsc-erigon:{{ .Version }}-arm64

  - name_template: ghcr.io/settlemint/bsc-erigon:latest
    skip_push: true
    image_templates:
      - ghcr.io/settlemint/bsc-erigon:{{ .Version }}-amd64
      # - ghcr.io/settlemint/bsc-erigon:{{ .Version }}-arm64

announce:
  slack:
    enabled: false
    # The name of the channel that the user selected as a destination for webhook messages.
    channel: '#code-releases'
